casa/contacts/urls.py
from django.urls import path
from .views import (anonymous_contact, user_contact, chat_message,
                    MessageHistoryListView)


urlpatterns = [
    path('anonymous-contact', anonymous_contact, name='anonymous-contact'),
    path('user-contact', user_contact, name='user-contact'),
    path('chat', chat_message, name='chat'),
    path('history/<int:pk>', MessageHistoryListView.as_view(), name='chat-history'),
]

casa/core/urls.py
from django.urls import path

from .views import (IndexView, AboutView, ImpressumView, PrivacyView,
                    RobotsTXTView)

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('robots.txt', RobotsTXTView.as_view(content_type="text/plain")),
    path('about-us', AboutView.as_view(), name='about'),
    path('impressum', ImpressumView.as_view(), name="impressum"),
    path('privacy', PrivacyView.as_view(), name="privacy"),

]

casa/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from contacts.views import AdminContactView
from django.contrib.auth import views as auth_views
# from django.conf.urls import (handler400, handler403, handler404, handler500)

handler400 = 'core.views.bad_request'
handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


urlpatterns = i18n_patterns(
    path('i18n/', include('django_translation_flags.urls')),
    path('admin/', admin.site.urls),
    path('admin/contact/', AdminContactView.as_view(), name='admin-contact'),

    path('', include('core.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/auth/password_reset_done.html'),
         name='password-reset-done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(  # noqa
        template_name="accounts/auth/password_reset_confirm.html"),
         name='password-reset-confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/auth/password_reset_complete.html'),
         name='password_reset_complete'),

    path('listings/', include('listings.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('contacts/', include('contacts.urls')),
    path('listings/', include('documents.urls')),

)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

casa/contacts/models.py
from django.db import models
from datetime import datetime
from django.conf import settings
from django.utils.translation import ugettext_lazy as _



class Contact(models.Model):
    listing = models.ForeignKey('listings.Listing',
                                on_delete=models.DO_NOTHING,
                                verbose_name=_("Listing"))
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.PROTECT, verbose_name=_("User"))
    phone = models.CharField(max_length=100, verbose_name=_("Phone"))
    message = models.TextField(blank=True, verbose_name=_("Message"))
    contact_date = models.DateTimeField(default=datetime.now, blank=True,
                                        verbose_name=_("Contact date"))
    can_access_documents = models.BooleanField(default=False,
                                               verbose_name=_("Docs access"))

    class Meta:
        ordering = ['-contact_date']

    def __str__(self):
        return f"{self.listing} - {self.user}"

    def get_full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"
    get_full_name.short_description = _("Client")

    def get_email(self):
        return f"{self.user.email}"
    get_email.short_description = _("Email")


    
class ChatMessage(models.Model):
    contact = models.ForeignKey(Contact, on_delete=models.PROTECT,
                                verbose_name=_("Contact listing"))
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.PROTECT, verbose_name=_("User"))
    message = models.TextField(null=True, blank=False)
    timestamp = models.DateTimeField(default=datetime.now, blank=True,
                                     verbose_name=_("Date and iime"))

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return f"{self.contact} - {self.user} - {self.message}"

casa/contacts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.mail import send_mail
from .models import Contact, ChatMessage
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext_lazy as _
from django.core.paginator import Paginator
from django.views.generic import (DetailView, TemplateView)
from listings.models import Listing


def user_contact(request):
    if request.method == 'POST':
        listing_id = request.POST['listing_id']
        phone = request.POST['phone']
        message = request.POST['message']
        user_id = request.POST['user_id']
        realtor_email = request.POST['realtor_email']

        #  Check if user has made inquiry already
        if request.user.is_authenticated:
            user_id = request.user.id
            has_contacted = Contact.objects.all().filter(
                listing_id=listing_id, user_id=user_id)
            if has_contacted:
                messages.error(
                    request, _("You have already made an inquiry "
                               "for this listing"))
                return redirect('listing', listing_id)

        contact = Contact(listing_id=listing_id, phone=phone, message=message,
                          user_id=user_id)

        contact.save()

        # Send email
        send_mail(f'Property Listing Inquiry',
                  f'There has been an inquiry for '
                  f'{Listing.objects.get(id=listing_id)}'
                  f'. Sign into the admin panel for more info',
                  'schonefeld.dev@gmail.com',
                  [realtor_email, 'schonefeld.dev@gmail.com'],
                  fail_silently=False)

        messages.success(
            request, (_("Your request has been submitted, a realtor will "
                        "get back to you soon")))
        return redirect('/listings/' + listing_id)


def anonymous_contact(request):
    if request.method == 'POST':
        listing_id = request.POST['listing_id']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        phone = request.POST['phone']
        message = request.POST['message']
        realtor_email = request.POST['realtor_email']

        #  Check if user has made inquiry already
        if request.user.is_authenticated:
            user_id = request.user.id
            has_contacted = Contact.objects.all().filter(
                listing_id=listing_id, first_name=first_name,
                last_name=last_name)
            if has_contacted:
                messages.error(
                    request, _("You have already made an inquiry for this "
                               "listing"))
                return redirect('listing', pk=listing_id)

        contact = Contact(listing_id=listing_id, phone=phone, message=message,
                          user_id=user_id)

        contact.save()

        # Send email
        send_mail('Property Listing Inquiry',
                  'There has been an inquiry for '
                  + Listing.object.get(id=listing_id)
                  + '. Sign into the admin panel for more info',
                  'schonefeld.dev@gmail.com',
                  [realtor_email, 'schonefeld.dev@gmail.com'],
                  fail_silently=False)

        messages.success(
            request, (_("Your request has been submitted, a realtor will "
                        "get back to you soon")))
        return redirect('/listings/' + listing_id)


@login_required
def chat_message(request):
    if request.method == 'POST':
        contact_id = request.POST['contact_id']
        user_id = request.POST['user_id']
        message = request.POST['message']

        obj = ChatMessage(contact_id=contact_id, message=message,
                          user_id=user_id)

        obj.save()

        messages.success(
            request, (_("Your request has been submitted, a realtor will ' \
                        'get back to you soon")))
        return redirect('chat-history', pk=contact_id)


class MessageHistoryListView(DetailView):
    model = Contact
    template_name = 'contacts/messages_history.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Showcase Section Infos
        context['title'] = _("Message History")
        context['subtitle'] = self.object.listing.title
        # SEO
        context['page_title'] = _("Message History")
        context['page_description'] = _("Gerente de bienes raíces."
                                        "Here you can follow your message "
                                        "history, related to a specific "
                                        "listing you are interested in..")
        return context


class AdminContactView(TemplateView):
    # TODO finish this crap
    template_name = 'admin/contact.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contact'] = Contact.objects.get(id=5)
        return context

casa/templates/contacts/messages_history.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<section id="showcase-inner" class="py-5 text-white">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-4">{{ title }}</h1>
        <p class="lead">{{ subtitle }}</p>
      </div>
    </div>
  </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'index' %}">
            <i class="fas fa-home"></i>
            {{ _("Inicio") }}
          </a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'dashboard' %}">
            {{ _("Dashboard") }}
          </a>
        </li>
        <li class="breadcrumb-item active"> {{ _("Historial") }}</li>

      </ol>
    </nav>
  </div>
</section>

<!-- Alerts -->
{% include 'core/partials/_alerts.html' %}

<section id="dashboard" class="py-4">
  <div class="container">

    <div>
      {% if user.is_authenticated %}
      {% if object.user.id == user.id %}


      <div class="card mb-4">
        <div class="card-header">{{ _("Send new message") }}</div>
        <form action="{% url 'chat' %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="user_id" value="{{ user.id }}">
          <input type="hidden" name="contact_id" value="{{ object.id }}">

          <div class="form-group pl-2 pr-2 pt-2">

            <textarea name="message" class="form-control" rows="4" placeholder='{{ _("Enter message here please...") }}'
              required></textarea>

            <div class="row mt-2 mb-2">
              <div class="col-12 col-lg-6">
                <input type="submit" value="Send" class="btn btn-block btn-secondary">
              </div>
              <div class="col-12 col-lg-6">
                <button type="button" class="btn btn-outline-secondary btn-block"
                  onclick="history.back()">{{ _("Regresar") }}</button>
              </div>

            </div>
          </div>

        </form>
      </div>


      <div>
        <h2 class="text-center mb-5 mt-5">{{_("History") }}</h2>
      </div>

      <div>
        {% for message in object.chatmessage_set.all %}


        <div class="row {% if message.user.id == user.id%} chat-right 
                      {% else %} chat-left {% endif %} ml-0 mr-0">

          <div class="row col-md-4">
            <p class="col-12 mt-3 ml-3">{{ message.user.first_name }} {{ message.user.last_name }}</p>
            <small class="col-12 mb-3 ml-3 smaller-things">{{ message.timestamp }} </small>

          </div>
          <div class="col-md-8 vertical-center">
            <p class="pt-3 ml-3">{{ message.message }}</p>
          </div>

        </div>

        {% endfor %}
        {% else %}
        {{ _("Nothing to display") }}
        {% endif %}
      </div>

    </div>
  </div>
</section>
{% endif %}

{% endblock %}